### ISSUE TITLE
Broken chest texture

### ISSUE THREAD

**Issue by matthaigh27** [FoundationGames/EnhancedBlockEntities#35] opened 2021-06-23 00:51 UTC
The chest texture seems to be broken when opening and closing. I took the below just after escaping out of it. I am currently using with sodium as per the guide.
![2021-06-23_10 48 58](https://user-images.githubusercontent.com/44395485/123017876-d4d18c00-d410-11eb-9eee-95c372a632c7.png)

**Comment by FoundationGames** [comment] 2021-06-23 01:25
Could you please provide a full mod list?

**Comment by edwloef** [comment] 2021-07-08 12:09
I have this issue as well, this is my modlist:
![Screenshot from 2021-07-08 14-09-39](https://user-images.githubusercontent.com/75493688/124919147-2aec2500-dff6-11eb-8e39-62e1ee6c3d2c.png)

**Comment by JustinNitoi** [comment] 2021-07-10 00:48
I also have the same issue

**Comment by FoundationGames** [comment] 2021-07-10 01:08
The new sodium versions for 1.17 are not final and have several known bugs, no support will be provided for this unless the issue is proven to still occur without sodium

**Comment by edwloef** [comment] 2021-07-10 06:03
Ah sorry, seems to be fixed with the latest sodium commit.

**Closed as completed** 2021-07-14 23:56 UTC

**Comment by mrgrim** [comment] 2021-07-20 19:01
This issue remains now that sodium and indium have proper releases for 1.17.1, but I'm not sure if this issue should be re-opened, a new one created, or if the issue is with this mod, indium, or sodium. If something else in the chunk causes an update that results in a the renderer updating it then the issue will correct itself.

During the development cycle of sodium for 1.17.1 there was an issue where placed block entities like shulker boxes wouldn't render until the camera moved, and the bug was that such actions were not given some sort of priority flag for rebuilding the chunk. That specific issue was fixed, but I'm wondering if the issue here is something similar, where removing the block from the chunk rendering during the animation needs some sort of priority flag to request the renderer process the change immediately?

**Comment by Kroppeb** [comment] 2021-07-20 22:48
> During the development cycle of sodium for 1.17.1 there was an issue where placed block entities like shulker boxes wouldn't render until the camera moved, and the bug was that such actions were not given some sort of priority flag for rebuilding the chunk.

No the issue was that priority updates didn't trigger the chunk culler, which is responsible for telling the renderer which chunks to draw, and by extension which block entities to draw. Asking the culler to recalculate does come with a performance penalty, so it might be better to bypass it and manually add/remove the block entity from the internal drawing list?
