### ISSUE TITLE
Chests are invisible with Sodium

### ISSUE THREAD

**Issue by PRiesebos** [FoundationGames/EnhancedBlockEntities#3] opened 2021-03-01 14:20 UTC
![2021-03-01_15 18 10](https://user-images.githubusercontent.com/23739238/109509752-85520380-7aa1-11eb-82c4-dcfa8c276487.png)

Chests don't show using a resourcepack and the following mods:
Sodium 1.1.0
Sodium-extra-0.2.0

**Comment by FoundationGames** [comment] 2021-03-01 16:14
This mod is incompatible with sodium on its own. If you would like to use this with sodium, use [Indium](https://github.com/comp500/Indium), a mod which allows special rendering (like used in ebe) to work on sodium.

**Comment by FoundationGames** [comment] 2021-03-01 18:04
Found the cause of the issue, unrelated to fabric rendering api and in fact is a minor issue in sodium.

**Comment by DragonEggBedrockBreaking** [comment] 2021-03-12 16:04
The pull request has been merged, so should this be closed?

**Comment by FoundationGames** [comment] 2021-03-17 21:14
Closing now.
Reason: merged sodium PR solving this issue

**Closed as completed by FoundationGames** 2021-03-17 21:14 UTC
