### ISSUE TITLE
Breaking particles visual glitch

### ISSUE THREAD

**Issue by thefrogfish** [FoundationGames/EnhancedBlockEntities#15] opened 2021-03-23 00:05 UTC
~~mod list~~
-fabric-api-0.32.5+1.16
-enhancedblockentities-0.1--1.16.x

--images below-

![2021-03-22_19 56 40](https://user-images.githubusercontent.com/81198975/112072880-34d24100-8b49-11eb-876a-05af0bef90ea.png)
![2021-03-22_19 56 33](https://user-images.githubusercontent.com/81198975/112072888-37349b00-8b49-11eb-8016-50ec5a26e6b5.png)

**Comment by FoundationGames** [comment] 2021-03-23 00:27
I don't see what the issue is. The particles appear the way they do since they use the vanilla chest textures rather than plank/obsidian textures.
Please clarify within a few days, or the issue will be closed. Thanks!

**Comment by thefrogfish** [comment] 2021-03-23 14:00
just wondering if its possible to have the plank/obsidian textures instead of the chest/ender chest texture when using this mod

**Comment by Xrey274** [comment] 2021-03-26 08:26
> I don't see what the issue is. The particles appear the way they do since they use the vanilla chest textures rather than plank/obsidian textures.
> Please clarify within a few days, or the issue will be closed. Thanks!

What I'm seeing from these pictures is that particles uses the whole texture. Particles from other blocks use just a couple pixels, not the whole texture just downscaled.

**Comment by FoundationGames** [comment] 2021-04-17 20:25
The chest block texture is an entity texture, which is 64x64 with all faces unwrapped. Block dust particles use small portions of the provided particle texture as their own texture. As the chest face textures on the chest entity texture take up only a fraction of the texture's area, it appears as if "the entire texture" is being displayed on the particle despite it being normal vanilla behavior.

**Comment by Xrey274** [comment] 2021-04-26 06:20
Technically you can say it's normal behavior, but it still looks weird/bad. Perhaps only use one of the faces for the particles?
At https://vanillatweaks.net/picker/resource-packs/ , under the **Fixes** tab there is a resource pack called "Proper Break Particles". Perhaps try to emulate the way it looks. It only uses the top face of chests.

**Comment by CalXee** [comment] 2021-04-30 15:55
I agree it looks bad, the particles aren't square or rectangle anymore and contains too much vertices, making it very unminecrafty. Imo, the baked models particles look better, especially with the fixed vanilla tweaks texture pack Xrey brought up.

**Comment by CalXee** [comment] 2021-05-09 22:10
This issue can be easily fixed for bells, but for chests (and other blocks with variants), I need to gain a better understanding of what #chest means in models/block. #chest governs the particles for both ender chests and chests, and assigns particles accordingly.

**Comment by FoundationGames** [comment] 2021-05-10 00:04
#chest actually also governs that texture applied to the actual chest model. Changing it to planks will not work.

**Comment by FoundationGames** [comment] 2021-05-21 00:53
This has been "fixed" in the last 2 commits to 116_indev, will be available upon next release

**Comment by CalXee** [comment] 2021-05-27 16:21
This has been fixed in the latest commit for all chest types, but not fixed for signs and beds.

**Closed as completed** 2021-07-08 18:49 UTC
